trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'
pool:
  vmImage: $(imageName)
steps:
- task: NodeTool@0
  inputs:
    versionSpec: '11.x'
  displayName: 'Install Node.js'
- bash: npm install"
  displayName: Install dependencies
- script: npm run generate
  displayName: Generate tree-sitter lexer/parser
- bash: npm run test-only
  displayName: Run parser tests