trigger: none

pool:
  vmImage: ubuntu-latest
steps:
- task: NodeTool@0
  inputs:
    versionSpec: 11.x
  displayName: install node
- bash: npx commitlint --from origin/master --to HEAD
  displayName: verify commits
