trigger: none

jobs:
- job: commit_verifier
  displayName: verify commits
  pool:
    vmImage: ubuntu-latest
  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: 11.x
    displayName: install node
  - bash: npm install && npx commitlint --from origin/master --to HEAD
    displayName: verify commits
- job: build
  displayName: build
  strategy:
    matrix:
      linux:
        osName: linux
        imageName: 'ubuntu-16.04'
      mac:
        osName: macos
        imageName: 'macos-10.13'
      windows:
        osName: windows
        imageName: 'vs2017-win2016'
  pool:
    vmImage: $(imageName)
  steps:
  - checkout: self
    submodules: true
  - task: NodeTool@0
    inputs:
      versionSpec: 11.x
    displayName: install node
  - bash: npm ci
    displayName: install module
  - bash: npm run unit-test-only
    displayName: run parser unit tests
  - bash: npm run example-test-only
    displayName: run parser example tests
  - bash: npm pack
    displayName: package npm module
  - bash: npm run package-test-only
    displayName: test packaging
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '*.tgz'
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
    displayName: copy npm package
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: 'package.json'
      targetFolder: $(Build.ArtifactStagingDirectory)/npm
    displayName: copy package.json
  - publish: '$(Build.ArtifactStagingDirectory)/npm'
    artifact: npm-$(osName)
