trigger:
- master

pr: none

pool:
  vmImage: ubuntu-latest
steps:
  - checkout: self
    submodules: true
  - task: NodeTool@0
    inputs:
      versionSpec: 11.x
    displayName: install node
  - bash: npm ci
    displayName: install module
  - bash: npx semantic-release
    displayName: semantic release
    env:
      GH_TOKEN: $(GH_TOKEN)
      NPM_TOKEN: $(NPM_TOKEN)
      BUILD_SOURCEBRANCHNAME: $(Build.SourceBranchName)
